### ISSUE TITLE
Figure Out Configurations On Runner Dockerfile

### ISSUE THREAD

**Issue by Gamma169** [Gamma169/go-service-template#1] opened 2021-11-06 23:25 UTC
I copied the arg values from the builder container into the runner container.

https://github.com/Gamma169/go-service-template/blob/09f3449fad2292d4ac0e1cf4038d8fffb1ada9de/Dockerfile#L34

This generally isn't good since we would need to update configurations in two spots.  Should see if we can use the same configurations for both.

Also, the CMD is hardcoded.   Need to figure out a way to get the app name configurable into the CMD.

**Comment by franklinchou** [comment] 2021-12-29 16:46
This is sort of a "feature"; it's expected behavior of the multi-stage Docker build. This is from the documentation:

"An `ARG` instruction goes out of scope at the end of the build stage where it was defined. To use an arg in multiple stages, each stage must include the `ARG` instruction." (See [here](https://docs.docker.com/engine/reference/builder/#arg).) However, it does seem that if an `ARG` is needed in later stages, simply indicating that the `ARG` is expected will allow use of the `ARG` value set in the previous stage.

**Comment by franklinchou** [comment] 2021-12-29 17:05
> Also, the CMD is hardcoded. Need to figure out a way to get the app name configurable into the CMD.


https://github.com/Gamma169/go-service-template/blob/75d3e395f3defd78a7758ad8b54188abe17c2c57/Dockerfile#L34

^ Adding this line should fix this. The reason is b/c `ARG`s are only available at build time (i.e., `ARG`s don't persist after the image is built). A `CMD` is executed at run time so the `ARG` isn't available anymore. Making the `ARG` an environment variable should do the trick, since `ENV` **does** persist into runtime.

**Closed as completed** 2021-12-29 22:23 UTC
